"""add alert tables

Revision ID: afce65cc22fd
Revises: d5e6f7a8b9c0
Create Date: 2026-04-23 00:45:43.263305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afce65cc22fd'
down_revision: Union[str, Sequence[str], None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_name'), 'alert_rules', ['name'], unique=True)
    op.create_index(op.f('ix_alert_rules_rule_type'), 'alert_rules', ['rule_type'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('context_key', sa.String(length=512), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_context_key'), 'alert_history', ['context_key'], unique=False)
    op.create_index(op.f('ix_alert_history_state'), 'alert_history', ['state'], unique=False)
    op.create_table('alert_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('context_key', sa.String(length=512), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_states_context_key'), 'alert_states', ['context_key'], unique=False)
    op.create_index(op.f('ix_alert_states_state'), 'alert_states', ['state'], unique=False)
    op.drop_index(op.f('ix_digest_records_created_at'), table_name='digest_records')
    op.drop_index(op.f('ix_event_score_rules_event_type'), table_name='event_score_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_score_rules_event_type'), 'event_score_rules', ['event_type'], unique=1)
    op.create_index(op.f('ix_digest_records_created_at'), 'digest_records', ['created_at'], unique=False)
    op.drop_index(op.f('ix_alert_states_state'), table_name='alert_states')
    op.drop_index(op.f('ix_alert_states_context_key'), table_name='alert_states')
    op.drop_table('alert_states')
    op.drop_index(op.f('ix_alert_history_state'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_context_key'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_alert_rules_rule_type'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_name'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
