"""initial_schema

Revision ID: c4d27748ae50
Revises: 
Create Date: 2026-03-21 23:02:31.836964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d27748ae50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcenters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=512), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=512), nullable=False),
    sa.Column('password', sa.String(length=2048), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vcenters_name'), 'vcenters', ['name'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcenter_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=512), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=64), nullable=True),
    sa.Column('user_name', sa.String(length=512), nullable=True),
    sa.Column('entity_name', sa.String(length=1024), nullable=True),
    sa.Column('entity_type', sa.String(length=256), nullable=True),
    sa.Column('vmware_key', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('notable_score', sa.Integer(), nullable=False),
    sa.Column('notable_tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['vcenter_id'], ['vcenters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vcenter_id', 'vmware_key', name='uq_event_vcenter_vmware_key')
    )
    op.create_index(op.f('ix_events_entity_name'), 'events', ['entity_name'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_notable_score'), 'events', ['notable_score'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_vmware_key'), 'events', ['vmware_key'], unique=False)
    op.create_table('ingestion_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcenter_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('cursor_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vcenter_id'], ['vcenters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vcenter_id', 'kind', name='uq_ingestion_vcenter_kind')
    )
    op.create_index(op.f('ix_ingestion_state_kind'), 'ingestion_state', ['kind'], unique=False)
    op.create_table('metric_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcenter_id', sa.Uuid(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_moid', sa.String(length=256), nullable=False),
    sa.Column('entity_name', sa.String(length=1024), nullable=False),
    sa.Column('metric_key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vcenter_id'], ['vcenters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vcenter_id', 'sampled_at', 'entity_moid', 'metric_key', name='uq_metric_sample_point')
    )
    op.create_index(op.f('ix_metric_samples_entity_moid'), 'metric_samples', ['entity_moid'], unique=False)
    op.create_index(op.f('ix_metric_samples_entity_type'), 'metric_samples', ['entity_type'], unique=False)
    op.create_index(op.f('ix_metric_samples_metric_key'), 'metric_samples', ['metric_key'], unique=False)
    op.create_index(op.f('ix_metric_samples_sampled_at'), 'metric_samples', ['sampled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_samples_sampled_at'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_metric_key'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_entity_type'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_entity_moid'), table_name='metric_samples')
    op.drop_table('metric_samples')
    op.drop_index(op.f('ix_ingestion_state_kind'), table_name='ingestion_state')
    op.drop_table('ingestion_state')
    op.drop_index(op.f('ix_events_vmware_key'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_notable_score'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_entity_name'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_vcenters_name'), table_name='vcenters')
    op.drop_table('vcenters')
    # ### end Alembic commands ###
